# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  push_to_registries:
    if: github.repository == 'lujiajing1126/docker-elasticsearch-alpine'
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        version: [6.2.4, 6.3.2, 6.4.3, 6.5.4, 6.6.2, 6.7.2, 6.8.23, 7.0.1, 7.1.1, 7.2.1, 7.3.2, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 7.10, 7.15, 7.16, 7.17]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set context dir
        run: echo "DOCKER_DIR=$(echo ${{ matrix.version }} | cut -d. -f1-2)" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        timeout-minutes: 20
        with:
          context: ./${{ DOCKER_DIR }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/lujiajing1126/elasticsearch:${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
